name: Setup prerequisites
description: Setup pnpm and Node.js
runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8.x

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: pnpm

    - name: Create env file for prepare scripts
      shell: bash
      run: |
        echo "NODE_ENV=production" > .env
