name: Test Server and Client

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Start Foundry Node
        run: pnpm dev:node &

      - name: Deploy contracts
        run: pnpm deploy:contracts:local

      - name: Test
        run: pnpm test
