name: Test Server and Client

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install dependencies
        run: pnpm install --prefer-frozen-lockfile --ignore-scripts

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Start Foundry Node
        run: pnpm dev:node &

      - name: Add Foundry private key
        run: echo "PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80" > packages/test-contracts/.env

      - name: Deploy contracts
        run: pnpm deploy:contracts:local

      - name: Test
        run: pnpm test
